# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappmel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://melanienube.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_10f1efb0d3c14157b9921d782eb76ed0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_751d22272cf24f0c9332a7f2939e280d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: melanienube.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10f1efb0d3c14157b9921d782eb76ed0 }}/melcontainer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappmel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_019c6f57ee5f47259971b07324c5bffe }}
        images: 'melanienube.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10f1efb0d3c14157b9921d782eb76ed0 }}/melcontainer:${{ github.sha }}'